module.exports = {
  CHANGE_GAME_STATE: 0,
  JOIN_GAME: 0,
  MOVE_CARD: 0,
  WAIT_PROMISE: 0,

  // Game initialization actions
  INITIALIZE_DECKS: 590,
  INITIALIZE_GAME_CONTAINERS: 580,
  INITIALIZE_GAME_CARD: 560,
  INITIALIZE_GAME_FINISHED: 520,
  INITIALIZE_GAME_CLOSED: 510,

  INITIALIZE_PLAYER_CONTAINERS: 490,
  SETUP_PLAYER_CONTAINER: 480,
  INITIALIZE_PLAYER_FINISHED: 420,
  INITIALIZE_PLAYER_CLOSED: 410,
  INITIALIZE_PLAYER_START: 400,
};
