export const MOVE_CARD = 'MOVE_CARD';
export const GAME_STATE_ARRIVED = 'GAME_STATE_ARRIVED';

export const DECKS_ARRIVED = 'DECKS_ARRIVED';
export const PLAYERS_ARRIVED = 'PLAYERS_ARRIVED';
export const HOLDERS_ARRIVED = 'HOLDERS_ARRIVED';

export const PLAYER_UPDATED = 'PLAYER_UPDATED';
export const DECK_UPDATED = 'DECK_UPDATED';
export const HOLDER_UPDATED = 'HOLDER_UPDATED';

export const HOLDER_CARD_INSERTED = 'HOLDER_CARD_INSERTED';
export const HOLDER_CARD_REMOVED = 'HOLDER_CARD_REMOVED';
